name: render and publish article

on: [push]

jobs:

  build:

    name: render

    runs-on: ubuntu-latest

    steps:

      - name: shallow checkout
        uses: actions/checkout@v1.0.0
        with:
          ref: refs/heads/master
          fetch-depth: 1

      - name: install dependencies
        run: sudo apt-get install make pandoc

      - name: render document
        run: make

      - name: publish to pages
        uses: peaceiris/actions-gh-pages@v1.1.0
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
